### ISSUE TITLE
Why are we streaming JSON here, but using JSON.stringify in Koa itself?

### ISSUE THREAD

**Issue by PlasmaPower** [koajs/json#13]
I think that the defaults should be the same for both of these. I get that this is an addon, but if one method is better, then why not use that one for both?

**Comment by tj** [comment]
I'm no help there, originally it was just middleware that allowed you to add `?pretty` for formatted responses. Object streams are a hack, not really core material IMO

**Comment by PlasmaPower** [comment]
Oops nevermind, I misread the code. I thought it was streaming when JSON was passed to it. It's only streaming when a stream is passed to it.
