### ISSUE TITLE
when i use compose middlewares  koa routes run two times

### ISSUE THREAD

**Issue by flashYang** [koajs/json#19]
this is my code 
```
const middlewares = compose([
	favicon(__dirname + '/favicon.ico'),
	bodyParser({formLimit: '5mb'}),
    json(),
    router.routes(),
	router.allowedMethods()
])

app.use(middlewares)

```

**Comment by coderhaoxin** [comment]
> koa routes run two times

Can you get the request path? Maybe one is `/favicon.ico`.

Anyway, I don't think it's related with this module! >_<

**Comment by flashYang** [comment]
![image](https://cloud.githubusercontent.com/assets/10190366/16252783/af240576-3863-11e6-9ea7-e9603ca9da32.png)
when i remove this module, the router work normal

**Comment by coderhaoxin** [comment]
Can you give a whole example to reproduce this ?

**Comment by flashYang** [comment]
I am on 18th floor, Let's talk face to face,or I can go upstair .

**Comment by coderhaoxin** [comment]
Chrome extension trigger second request >_<
