### ISSUE TITLE
Empty response when result contains null or undefined values

### ISSUE THREAD

**Issue by damianobarbati** [koajs/json#20]
If route returns null or undefined or an object with a null or undefined property then body/response is empty!

```
app.use(async (ctx, next) => {
	try {
    	      await next();
    	      ctx.body = null; //empty response
    	      ctx.body = undefined; //empty response
    	      ctx.body = { data: null }; //empty response
    	      ctx.body = { data: undefined }; //empty response
  	}
	catch(error) {
	    	ctx.status = 400;
		ctx.body = error.message || error;
	}
});

```

**Comment by coderhaoxin** [comment]
@damianobarbati 

1. `undefined` is not valid json data type. https://www.tutorialspoint.com/json/json_data_types.htm

```js
JSON.stringify({ foo: undefined }) // => '{}'
```

2. 

```js
ctx.body = null; //empty response
ctx.body = undefined; //empty response
```

This is correct.

3.

```js
ctx.body = { data: null }; //empty response
```

I add a test for this.

https://github.com/koajs/json/blob/master/test/pretty.js#L25-L34

8b4bb53c48218867855390bf82f01fdd38400407

**Comment by damianobarbati** [comment]
7y after... @haoxins case 2 is wrong as you are removing a valid JSON value which is `null`:
```sh
ctx.body = null; // empty response <= wrong, there's a response carrying the `null` information
```

You are removing information from the payload.
Null is a valid JSON value that the developer cannot transmit with a valid JSON payload `null` with this package.
Instead, you are forcing the developers to always wrap the value into an object / different payload like `{"data":null}`.
