### ISSUE TITLE
Prettify automatically based on accept header

### ISSUE THREAD

**Issue by bschlenk** [koajs/json#21]
It would be nice if there was an option for the prettify to happen automatically based on an accept header, something like this:

```js
switch (ctx.accepts('json', 'html', 'text')) {
    json: break;
    html:
    text:
        // pretty print json here
    default: break;
}
```

**Comment by coderhaoxin** [comment]
SGTM, PR welcome :)

**Comment by 3imed-jaberi** [comment]
I think the current behavior is enough and better than the accepts header to detect and use the pretty option. If you insite to see it you can open a PR when I can give you some help ...
