### ISSUE TITLE
not working at all (because this.body is already stringifed json?)

### ISSUE THREAD

**Issue by jakeg** [koajs/json#6]
Module doesn't seem to be working at all for me.

```
...
app.use(require('koa-json')());

router.get('/test', function *(next) {
  this.body = {test: 'testing'};
});
...
```

... go to /test, doesn't look pretty.

Digging into the code I see that it doesn't print pretty if ```this.body``` is a string, but by the time koa-json code is run JSON seems to have been stringified already. Is my usage wrong or has koa changed how/when it stringifies JSON which means koa-json no longer works?

**Comment by jonathanong** [comment]
maybe you are mounting your router before using `koa-json`. do you mind making a PR with a failing test?

**Comment by jakeg** [comment]
seems this was conflicting with koa-compress. By moving koa-json to after koa-compress it works fine.

This doesn't work:

```
app.use(require('koa-json')({pretty: false, param: 'pretty'}));
app.use(require('koa-compress')());
```

This fixes it:

```
app.use(require('koa-compress')());
app.use(require('koa-json')({pretty: false, param: 'pretty'}));
```
