### ISSUE TITLE
`this.body` throw Error: Can't remove headers after they are sent.

### ISSUE THREAD

**Issue by freestyle21** [koajs/json#7]
Hello,

koa is a middleware in my scene, I use koa to send HTTP request and then reponse to browser.

here is my code:

    var reqHttp = http.request(opt, function(resHttp){
        if (resHttp.statusCode == 200){
            var buf = "";
            resHttp.on('data', function(data) {
                buf += data;
            });
            resHttp.on('end', function(){
                ctx.body = JSON.parse(buf); // throw error: Can't remove headers after they are sent.
            });
        } else {
            ctx.body = {error: -1};
        }
    });
    reqHttp.write(data);
    reqHttp.end();

I just want a like `res.json` in express for koa...

please help me ?

**Comment by freestyle21** [comment]
reqHttp.write(data);

the data comes from browser ajax request.

**Comment by jonathanong** [comment]
hi, unfortunately, this requires a big explanation about control flow. you're better off asking this question on stackoverflow :)

**Comment by OKNoah** [comment]
@freestyle21 Did you solve this?
